export { columnsGen } from "./columns";
export type { TranslationFn, Locals } from "./columns";
import { transformAllDataTables } from "../shared";
import type { Locals } from "./columns";

const initialColumnsArr = [
    ["pretty_name", true],
    ["instance_type", true],
    ["family", false],
    ["memory", true],
    ["ECU", false],
    ["vCPU", true],
    ["memory_per_vcpu", false],
    ["GPU", false],
    ["GPU_model", false],
    ["GPU_memory", false],
    ["compute_capability", false],
    ["FPGA", false],
    ["ECU_per_vcpu", false],
    ["physical_processor", false],
    ["clock_speed_ghz", false],
    ["intel_avx", false],
    ["intel_avx2", false],
    ["intel_avx512", false],
    ["intel_turbo", false],
    ["storage", true],
    ["warmed-up", false],
    ["trim-support", false],
    ["arch", false],
    ["network_performance", true],
    ["ebs_baseline_bandwidth", false],
    ["ebs_baseline_throughput", false],
    ["ebs_baseline_iops", false],
    ["ebs_max_bandwidth", false],
    ["ebs_throughput", false],
    ["ebs_iops", false],
    ["ebs_as_nvme", false],
    ["maxips", false],
    ["maxenis", false],
    ["enhanced_networking", false],
    ["vpc_only", false],
    ["ipv6_support", false],
    ["placement_group_support", false],
    ["linux_virtualization_types", false],
    ["emr", false],
    ["availability_zones", false],
    ["cost-ondemand", true],
    ["cost-reserved", true],
    ["cost-spot-min", true],
    ["cost-spot-max", false],
    ["cost-ondemand-rhel", false],
    ["cost-reserved-rhel", false],
    ["cost-spot-min-rhel", false],
    ["cost-spot-max-rhel", false],
    ["cost-ondemand-sles", false],
    ["cost-reserved-sles", false],
    ["cost-spot-min-sles", false],
    ["cost-spot-max-sles", false],
    ["cost-ondemand-mswin", true],
    ["cost-reserved-mswin", true],
    ["cost-spot-min-mswin", false],
    ["cost-spot-max-mswin", false],
    ["cost-ondemand-dedicated", false],
    ["cost-reserved-dedicated", false],
    ["cost-ondemand-mswinSQLWeb", false],
    ["cost-reserved-mswinSQLWeb", false],
    ["cost-ondemand-mswinSQL", false],
    ["cost-reserved-mswinSQL", false],
    ["cost-ondemand-mswinSQLEnterprise", false],
    ["cost-reserved-mswinSQLEnterprise", false],
    ["cost-ondemand-linuxSQLWeb", false],
    ["cost-reserved-linuxSQLWeb", false],
    ["cost-ondemand-linuxSQL", false],
    ["cost-reserved-linuxSQL", false],
    ["cost-ondemand-linuxSQLEnterprise", false],
    ["cost-reserved-linuxSQLEnterprise", false],
    ["spot-interrupt-rate", false],
    ["cost-emr", false],
    ["generation", false],
    ["coremark_iterations_second", true],
    ["gpu_architectures", false],
    ["gpu_current_temp_avg_celsius", false],
    ["gpu_power_max_watts_avg", false],
    ["ffmpeg_used_cuda", false],
    ["ffmpeg_speed", false],
    ["ffmpeg_fps", true],
    ["gpu_power_draw_watts_avg", false],
    ["gpu_clocks_graphics_avg", false],
    ["gpu_clocks_sm_avg", false],
    ["gpu_clocks_memory_avg", false],
    ["gpu_clocks_video_avg", false],
    ["memory_speed", false],
    ["uses_numa_architecture", false],
    ["numa_node_count", false],
    ["max_numa_distance", false],
    ["core_count_per_numa_node", false],
    ["thread_count_per_numa_node", false],
    ["memory_per_numa_node_mb", false],
    ["l3_per_numa_node_mb", false],
    ["l3_shared", false],
    ["compute_family", true],
    ["cost-ondemand-rhelHA", false],
    ["cost-reserved-rhelHA", false],
    ["cost-spot-min-rhelHA", false],
    ["cost-spot-max-rhelHA", false],
] as const;

export const initialColumnsValue: {
    [idx in (typeof initialColumnsArr)[number][0]]: boolean;
} = {} as any;
for (const [key, value] of initialColumnsArr) {
    initialColumnsValue[key] = value;
}

export function transformDataTables(dataTablesData: any) {
    return transformAllDataTables(initialColumnsArr, dataTablesData);
}

export function makePrettyNames<V>(
    makeColumnOption: (
        key: keyof typeof initialColumnsValue,
        label: string,
    ) => V,
    locals?: Locals,
) {
    const t = locals?.t;
    return [
        makeColumnOption("pretty_name", t?.("columns.common.name") ?? "Name"),
        makeColumnOption("instance_type", t?.("columns.common.apiName") ?? "API Name"),
        makeColumnOption("family", t?.("columns.common.instanceFamily") ?? "Instance Family"),
        makeColumnOption("compute_family", t?.("columns.common.computeFamily") ?? "Compute Family"),
        makeColumnOption("coremark_iterations_second", t?.("columns.ec2.coremarkScore") ?? "CoreMark Score"),
        makeColumnOption("ffmpeg_fps", t?.("columns.ec2.ffmpegFps") ?? "FFmpeg FPS"),
        makeColumnOption("memory", t?.("columns.common.memory") ?? "Memory"),
        makeColumnOption("memory_speed", t?.("columns.ec2.memorySpeed") ?? "Memory Speed"),
        makeColumnOption("uses_numa_architecture", t?.("columns.ec2.usesNumaArch") ?? "Uses NUMA Architecture"),
        makeColumnOption("numa_node_count", t?.("columns.ec2.numaNodeCount") ?? "NUMA Node Count"),
        makeColumnOption("max_numa_distance", t?.("columns.ec2.maxNumaDistance") ?? "Max NUMA Distance"),
        makeColumnOption("core_count_per_numa_node", t?.("columns.ec2.coresPerNumaNode") ?? "Cores per NUMA Node (Avg)"),
        makeColumnOption("thread_count_per_numa_node", t?.("columns.ec2.threadsPerNumaNode") ?? "Threads per NUMA Node (Avg)"),
        makeColumnOption("memory_per_numa_node_mb", t?.("columns.ec2.memoryPerNumaNode") ?? "Memory per NUMA Node (Avg MB)"),
        makeColumnOption("l3_per_numa_node_mb", t?.("columns.ec2.l3PerNumaNode") ?? "L3 Cache per NUMA Node (Avg MB)"),
        makeColumnOption("l3_shared", t?.("columns.ec2.l3CacheShared") ?? "L3 Cache Shared"),
        makeColumnOption("ECU", t?.("columns.ec2.computeUnitsEcu") ?? "Compute Units (ECU)"),
        makeColumnOption("vCPU", t?.("columns.common.vCPUs") ?? "vCPUs"),
        makeColumnOption("memory_per_vcpu", t?.("columns.common.memoryPerVcpu") ?? "GiB of Memory per vCPU"),
        makeColumnOption("GPU", t?.("columns.common.gpus") ?? "GPUs"),
        makeColumnOption("GPU_model", t?.("columns.common.gpuModel") ?? "GPU model"),
        makeColumnOption("GPU_memory", t?.("columns.common.gpuMemory") ?? "GPU memory"),
        makeColumnOption("compute_capability", t?.("columns.ec2.cudaComputeCapability") ?? "CUDA Compute Capability"),
        makeColumnOption("FPGA", t?.("columns.ec2.fpgas") ?? "FPGAs"),
        makeColumnOption("ECU_per_vcpu", t?.("columns.ec2.ecuPerVcpu") ?? "ECU per vCPU"),
        makeColumnOption("physical_processor", t?.("columns.common.physicalProcessor") ?? "Physical Processor"),
        makeColumnOption("clock_speed_ghz", t?.("columns.ec2.clockSpeed") ?? "Clock Speed(GHz)"),
        makeColumnOption("intel_avx", t?.("columns.ec2.intelAvx") ?? "Intel AVX"),
        makeColumnOption("intel_avx2", t?.("columns.ec2.intelAvx2") ?? "Intel AVX2"),
        makeColumnOption("intel_avx512", t?.("columns.ec2.intelAvx512") ?? "Intel AVX-512"),
        makeColumnOption("intel_turbo", t?.("columns.ec2.intelTurbo") ?? "Intel Turbo"),
        makeColumnOption("storage", t?.("columns.common.instanceStorage") ?? "Instance Storage"),
        makeColumnOption("warmed-up", t?.("columns.ec2.storageWarmedUp") ?? "Instance Storage: already warmed-up"),
        makeColumnOption("trim-support", t?.("columns.ec2.storageTrimSupport") ?? "Instance Storage: SSD TRIM Support"),
        makeColumnOption("arch", t?.("columns.common.arch") ?? "Arch"),
        makeColumnOption("network_performance", t?.("columns.common.networkPerformance") ?? "Network Performance"),
        makeColumnOption("ebs_baseline_bandwidth", t?.("columns.ec2.ebsBaselineBandwidth") ?? "EBS Optimized: Baseline Bandwidth"),
        makeColumnOption("ebs_baseline_throughput", t?.("columns.ec2.ebsBaselineThroughput") ?? "EBS Optimized: Baseline Throughput (128K)"),
        makeColumnOption("ebs_baseline_iops", t?.("columns.ec2.ebsBaselineIops") ?? "EBS Optimized: Baseline IOPS (16K)"),
        makeColumnOption("ebs_max_bandwidth", t?.("columns.ec2.ebsMaxBandwidth") ?? "EBS Optimized: Max Bandwidth"),
        makeColumnOption("ebs_throughput", t?.("columns.ec2.ebsMaxThroughput") ?? "EBS Optimized: Max Throughput (128K)"),
        makeColumnOption("ebs_iops", t?.("columns.ec2.ebsMaxIops") ?? "EBS Optimized: Max IOPS (16K)"),
        makeColumnOption("ebs_as_nvme", t?.("columns.ec2.ebsAsNvme") ?? "EBS Exposed as NVMe"),
        makeColumnOption("maxips", t?.("columns.ec2.maxIps") ?? "Max IPs"),
        makeColumnOption("maxenis", t?.("columns.ec2.maxEnis") ?? "Max ENIs"),
        makeColumnOption("enhanced_networking", t?.("columns.ec2.enhancedNetworking") ?? "Enhanced Networking"),
        makeColumnOption("vpc_only", t?.("columns.ec2.vpcOnly") ?? "VPC Only"),
        makeColumnOption("ipv6_support", t?.("columns.ec2.ipv6Support") ?? "IPv6 Support"),
        makeColumnOption("placement_group_support", t?.("columns.ec2.placementGroupSupport") ?? "Placement Group Support"),
        makeColumnOption("linux_virtualization_types", t?.("columns.ec2.linuxVirtualization") ?? "Linux Virtualization"),
        makeColumnOption("emr", t?.("columns.ec2.onEmr") ?? "On EMR"),
        makeColumnOption("availability_zones", t?.("columns.ec2.availabilityZones") ?? "Availability Zones"),
        makeColumnOption("cost-ondemand", t?.("columns.pricing.linuxOnDemand") ?? "On Demand"),
        makeColumnOption("cost-reserved", t?.("columns.pricing.linuxReserved") ?? "Linux Reserved cost"),
        makeColumnOption("cost-spot-min", t?.("columns.pricing.linuxSpotMin") ?? "Linux Spot Minimum cost"),
        makeColumnOption("cost-spot-max", t?.("columns.pricing.linuxSpotAvg") ?? "Linux Spot Average cost"),
        makeColumnOption("cost-ondemand-rhel", t?.("columns.pricing.rhelOnDemand") ?? "RHEL On Demand cost"),
        makeColumnOption("cost-reserved-rhel", t?.("columns.pricing.rhelReserved") ?? "RHEL Reserved cost"),
        makeColumnOption("cost-spot-min-rhel", t?.("columns.pricing.rhelSpotMin") ?? "RHEL Spot Minimum cost"),
        makeColumnOption("cost-spot-max-rhel", t?.("columns.pricing.rhelSpotMax") ?? "RHEL Spot Maximum cost"),
        makeColumnOption("cost-ondemand-rhelHA", t?.("columns.pricing.rhelHaOnDemand") ?? "RHEL with HA On Demand cost"),
        makeColumnOption("cost-reserved-rhelHA", t?.("columns.pricing.rhelHaReserved") ?? "RHEL with HA Reserved cost"),
        makeColumnOption("cost-spot-min-rhelHA", t?.("columns.pricing.rhelHaSpotMin") ?? "RHEL with HA Spot Minimum cost"),
        makeColumnOption("cost-spot-max-rhelHA", t?.("columns.pricing.rhelHaSpotMax") ?? "RHEL with HA Spot Maximum cost"),
        makeColumnOption("cost-ondemand-sles", t?.("columns.pricing.slesOnDemand") ?? "SLES On Demand cost"),
        makeColumnOption("cost-reserved-sles", t?.("columns.pricing.slesReserved") ?? "SLES Reserved cost"),
        makeColumnOption("cost-spot-min-sles", t?.("columns.pricing.slesSpotMin") ?? "SLES Spot Minimum cost"),
        makeColumnOption("cost-spot-max-sles", t?.("columns.pricing.slesSpotMax") ?? "SLES Spot Maximum cost"),
        makeColumnOption("cost-ondemand-mswin", t?.("columns.pricing.windowsOnDemand") ?? "Windows On Demand cost"),
        makeColumnOption("cost-reserved-mswin", t?.("columns.pricing.windowsReserved") ?? "Windows Reserved cost"),
        makeColumnOption("cost-spot-min-mswin", t?.("columns.pricing.windowsSpotMin") ?? "Windows Spot Minimum cost"),
        makeColumnOption("cost-spot-max-mswin", t?.("columns.pricing.windowsSpotAvg") ?? "Windows Spot Average cost"),
        makeColumnOption("cost-ondemand-dedicated", t?.("columns.pricing.dedicatedHostOnDemand") ?? "Dedicated Host On Demand"),
        makeColumnOption("cost-reserved-dedicated", t?.("columns.pricing.dedicatedHostReserved") ?? "Dedicated Host Reserved"),
        makeColumnOption("cost-ondemand-mswinSQLWeb", t?.("columns.pricing.windowsSqlWebOnDemand") ?? "Windows SQL Web On Demand cost"),
        makeColumnOption("cost-reserved-mswinSQLWeb", t?.("columns.pricing.windowsSqlWebReserved") ?? "Windows SQL Web Reserved cost"),
        makeColumnOption("cost-ondemand-mswinSQL", t?.("columns.pricing.windowsSqlStdOnDemand") ?? "Windows SQL Std On Demand cost"),
        makeColumnOption("cost-reserved-mswinSQL", t?.("columns.pricing.windowsSqlStdReserved") ?? "Windows SQL Std Reserved cost"),
        makeColumnOption("cost-ondemand-mswinSQLEnterprise", t?.("columns.pricing.windowsSqlEntOnDemand") ?? "Windows SQL Ent On Demand cost"),
        makeColumnOption("cost-reserved-mswinSQLEnterprise", t?.("columns.pricing.windowsSqlEntReserved") ?? "Windows SQL Ent Reserved cost"),
        makeColumnOption("cost-ondemand-linuxSQLWeb", t?.("columns.pricing.linuxSqlWebOnDemand") ?? "Linux SQL Web On Demand cost"),
        makeColumnOption("cost-reserved-linuxSQLWeb", t?.("columns.pricing.linuxSqlWebReserved") ?? "Linux SQL Web Reserved cost"),
        makeColumnOption("cost-ondemand-linuxSQL", t?.("columns.pricing.linuxSqlStdOnDemand") ?? "Linux SQL Std On Demand cost"),
        makeColumnOption("cost-reserved-linuxSQL", t?.("columns.pricing.linuxSqlStdReserved") ?? "Linux SQL Std Reserved cost"),
        makeColumnOption("cost-ondemand-linuxSQLEnterprise", t?.("columns.pricing.linuxSqlEntOnDemand") ?? "Linux SQL Ent On Demand cost"),
        makeColumnOption("cost-reserved-linuxSQLEnterprise", t?.("columns.pricing.linuxSqlEntReserved") ?? "Linux SQL Ent Reserved cost"),
        makeColumnOption("spot-interrupt-rate", t?.("columns.pricing.linuxSpotInterrupt") ?? "Linux Spot Interrupt Frequency"),
        makeColumnOption("cost-emr", t?.("columns.pricing.emrCost") ?? "EMR cost"),
        makeColumnOption("generation", t?.("columns.common.generation") ?? "Generation"),
        makeColumnOption("gpu_architectures", t?.("columns.ec2.gpuArchitectures") ?? "GPU Architectures"),
        makeColumnOption("gpu_current_temp_avg_celsius", t?.("columns.ec2.gpuTempAvg") ?? "GPU Temp (Avg °C)"),
        makeColumnOption("ffmpeg_used_cuda", t?.("columns.ec2.ffmpegUsedCuda") ?? "FFmpeg Used CUDA"),
        makeColumnOption("ffmpeg_speed", t?.("columns.ec2.ffmpegSpeed") ?? "FFmpeg Speed"),
        makeColumnOption("gpu_power_draw_watts_avg", t?.("columns.ec2.gpuPowerDrawAvg") ?? "GPU Power Draw (Avg Watts)"),
        makeColumnOption("gpu_power_max_watts_avg", t?.("columns.ec2.gpuPowerLimit") ?? "GPU Power Max (Avg Watts)"),
        makeColumnOption("gpu_clocks_graphics_avg", t?.("columns.ec2.gpuGraphicsClockAvg") ?? "GPU Graphics Clock (Avg MHz)"),
        makeColumnOption("gpu_clocks_sm_avg", t?.("columns.ec2.gpuSmClockAvg") ?? "GPU SM Clock (Avg MHz)"),
        makeColumnOption("gpu_clocks_memory_avg", t?.("columns.ec2.gpuMemoryClockAvg") ?? "GPU Memory Clock (Avg MHz)"),
        makeColumnOption("gpu_clocks_video_avg", t?.("columns.ec2.gpuVideoClockAvg") ?? "GPU Video Clock (Avg MHz)"),
    ];
}
