name: Tests
on: push

jobs:
    gofmt:
        name: gofmt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-go@v5
              with:
                  go-version: 1.24.4
            - name: Check gofmt
              run: cd scraper && gofmt -l . && test -z "$(gofmt -l .)"

    prettier:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-npm-prettier
                  restore-keys: |
                      ${{ runner.os }}-npm-
            - run: npm install -g prettier@3.5.3
            - run: |-
                  prettier --check .

    tests:
        name: Check Types and Run Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: un-tar the staging www at the root of the repo
              run: curl -L https://instances.vantagestaging.sh/www_pre_build.tar.gz | tar -xzf -
            - uses: actions/setup-node@v4
              with:
                  node-version-file: next/.nvmrc
            - name: Initialize the test environment
              run: cd next && npm ci && npm run init
            - name: Check types
              run: cd next && npm run check-types
            - name: Run unit tests
              run: cd next && npm run test -- --coverage
